[package]
name = "rsw-app"
version = "0.1.0"
authors = ["suren <suren>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
chrono = "0.4.0" 
uuid = { version = "0.8.1", features = ["v4"] }